### PR TITLE
fix(package): update cordova to 9.0.0

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
@purplecabbage do you have an estimate of a release with cordova 9 in it?

**Comment by purplecabbage** [comment]
should be there by Monday, I'll ping you.

**Comment by hdiniz** [comment]
@purplecabbage we are waiting on the update to 9.0.0, do you have a new estimate?

**Comment by purplecabbage** [comment]
@AdriVanHoudt @hdiniz 
Please give phonegap@next a try, and if all is good I will promote it to `latest`
`npm i -g phonegap@next`

**Comment by purplecabbage** [comment]
@AdriVanHoudt @hdiniz did you get a chance to try phonegap@next ?

**Comment by hdiniz** [comment]
@purplecabbage Yes, we did try the `@next`, it works! Thanks!
Right now we are using the `9.0.0-rc1` and the build works locally, but we are having a problem building it on PhonegapBuild. Do you know what could be the issue?

```
Check dependencies
warning: The armv7 architecture is deprecated for your deployment target (iOS 11.0). You should update your ARCHS build setting to remove the armv7 architecture.
The "Swift Language Version" (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The "Swift Language Version" (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

** ARCHIVE FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by purplecabbage** [comment]
Thanks, I will publish it to @latest tonite
re: build.phonegap.com 
Did you add this to your config.xml to tell build to target cordova@9.0.0?
    
    <preference name="phonegap-version" value="cli-9.0.0" />

**Comment by AdriVanHoudt** [comment]
I don't think anything changed really since https://github.com/phonegap/phonegap-cli/commit/17d4d0fff368d336e948e169485bb95e799affee? Which we've been using and which works

**Pull request merged**
