### PR TITLE
Data needs to be explicitly logged as utf8 in node >v6.2.1

### LINKED ISSUE #603: Strange <Buffer 0a> issue with phonegap-cli commands
Hi,

I've got a strange issue with the phonegap-cli where any command I use ends up with loads of `<Buffer ...` message being printed to my screen, and then it exits with no debug message at all.

````
➤ phonegap platform update android --verbose
(node:9925) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
<Buffer 55 70 64 61 74 69 6e 67 20 61 6e 64 72 6f 69 64 20 70 72 6f 6a 65 63 74 2e 2e 2e>
<Buffer 0a>
<Buffer 6c 73 3a 20 6e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 74 6f 72 79 3a 20 2f 55 73 65 72 73 2f 6d 61 74 74 2f 53 69 74 65 73 2f 67 ... >
<Buffer 41 6e 64 72 6f 69 64 20 70 72 6f 6a 65 63 74 20 75 70 64 61 74 65 64 20 77 69 74 68 20 63 6f 72 64 6f 76 61 2d 61 6e 64 72 6f 69 64 40 35 2e 31 2e 31>
<Buffer 0a>
<Buffer 6c 73 3a 20 6e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 74 6f 72 79 3a 20 2f 55 73 65 72 73 2f 6d 61 74 74 2f 53 69 74 65 73 2f 67 ... >
<Buffer 45 72 72 6f 72 3a 20 4e 6f 20 4a 61 76 61 20 66 69 6c 65 73 20 66 6f 75 6e 64 20 77 68 69 63 68 20 65 78 74 65 6e 64 20 43 6f 72 64 6f 76 61 41 63 74 ... >
````

I've just re-installed node (using Homebrew) & phonegap so I'm pretty sure I'm on the latest version of everything.

    ➤ node -v
    v6.2.1

    ➤ npm -v
    3.9.3

    ➤ phonegap -v
    (node:9975) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    6.2.6

It's worth noting that I previously had node v0.12 installed on this machine, and I upgraded it to v6.2.1 using Homebrew.

### PR DESCRIPTION
**Pull request by purplecabbage**
This fixes #603

### CODE REVIEW

**Comment by mwbrooks** [comment]
Wow, this ended up being a minor fix. Is it worth adding tests to recreate the output from Node 4.x/5.x and Node 6.x?

**Comment by surajpindoria** [comment]
I don't think we need tests. It is pretty minor and anything prior to this that is already in `utf8` format won't be effected.

**Comment by purplecabbage** [comment]
I did verify with+without the change in node v4.4.4, v5.12.0, v6.2.1

**Comment by surajpindoria** [comment]
Cool, I say let's merge this then

**Comment by surajpindoria** [comment]
Merged into master.

**Pull request closed without merging**
