### PR TITLE
Output url and qr code #627

### PR DESCRIPTION
**Pull request by purplecabbage**
This closes #612

### CODE REVIEW

**Comment by frederikbosch** [comment]
@purplecabbage The additional format parameters gives me the opportunity to do something with the url other than scanning a qr code (e.g. download the binary). While it is possible with this PR to still do that, it does not get any easier.

**Comment by purplecabbage** [comment]
Your pr will return `{"location":"https://build.phonegap.com/someapppath"}`
This pr returns `url: https://build.phonegap.com/someapppath`

It does not seem to be any easier/harder to me.  
Personally, I don't see it as worth adding a parameter that only you will use, can you explain your use-case little more.

**Comment by frederikbosch** [comment]
@purplecabbage This PR will return an url and a QR code. Sure, I can filter out the line that outputs `url:` instead of reading the last line with the json data. Use case: I want to download the resulting binaries to my local computer. The difference is not that big, so actually, I have no problem with this PR.

**Comment by purplecabbage** [comment]
Would you prefer the qr code first?

**Comment by frederikbosch** [comment]
I set the qr as default in order to stay backward compatible. Basically I want output that is easy readable by a non-human.

**Comment by frederikbosch** [comment]
Could this PR be merged?

**Pull request merged**
